package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.C3270g;
import com.google.android.gms.common.api.C3270g.C3271a;
import com.google.android.gms.common.api.C3391k;
import com.google.android.gms.common.api.C3392l;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

/* renamed from: com.google.android.gms.common.api.internal.bn */
public final class C3319bn<R extends C3391k> extends C3270g<R> {

    /* renamed from: a */
    private final Status f9619a;

    /* access modifiers changed from: 0000 */
    /* renamed from: d */
    public final Status mo13248d() {
        return this.f9619a;
    }

    /* renamed from: a */
    public final R mo13153a(long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo13154a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: b */
    public final boolean mo13157b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo13156a(C3392l<? super R> lVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo13155a(C3271a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: c */
    public final Integer mo13158c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
